### ISSUE TITLE
wired result (with NA involved)

### ISSUE THREAD

**Issue by ChingChuan-Chen** [alexcb/rjson#10]
I have some wired result in using rjson.

```r
x <- list(ss = c(123L, NA_integer_))

rjson::toJSON(x)
# [1] "{\"ss\":[123,\"NA\"]}"
```
`x` integer vector with `NA`, but `toJSON` gives integer and string.

```r
x <- list(ss = c(123L, NA_integer_))
rjson::fromJSON(rjson::toJSON(x))
# $ss
# $ss[[1]]
#  [1] 123
# $ss[[2]]
#  [1] "NA"
```
It is not equal to original `x`.

**Comment by alexcb** [comment]
There is no NA type in json; the `toJSON` converts NA into a string; when `fromJSON` doesn't perform any conversion from strings back into native R data types, as there's no way to know if the `"NA"` is a literal string from some other language or from rjson.
