### ISSUE TITLE
Convert strings with javascript escaped unicode properly

### ISSUE THREAD

**Issue by jefshe** [alexcb/rjson#11]
When using rjson to parse content JSON strings with javascript escaped characters: e.g. " #FOXSportsGO\n\ud83d\udcfb"

rjson will incorrectly parse this as an invalid utf-8 string ```"\xed\xa0\xbd\xed\xb3\xbb"```  instead of 📻.

**Comment by alexcb** [comment]
Can you please wrap this up in some R code I can copy and paste into R to replicated the issue.

**Comment by jefshe** [comment]
```R
rjson::fromJSON("{\"str\" : \"Anaheim Ducks \\ud83d\\ude0e\"}")
```
returns 
```
$str
[1] "Anaheim Ducks \xed\xa0\xbd\xed\xb8\x8e"
```
These garbage characters are not valid utf-8. The correct handling should be to convert the javascript string escapes properly:
```
$str
[1] "Anaheim Ducks 😎"
```

**Comment by alexcb** [comment]
Thanks for the great write-up @jefshe 

It looks like under the hood the unicode is being converted to a utf8 representation: https://github.com/alexcb/rjson/blob/master/rjson/src/parser.c#L311 but it has no logic to handle surrogate pairs.

for my own reference, here's an example of correctly handling this in python:
```
>>> import json
>>> x = "{\"str\" : \"Anaheim Ducks \\ud83d\\ude0e\"}"
>>> j = json.loads(x)
>>> j['str']
u'Anaheim Ducks \U0001f60e'
>>> print j['str']
Anaheim Ducks 😎
>>> j['str'].encode('utf8')
'Anaheim Ducks \xf0\x9f\x98\x8e'
```

Here's an example of rjson working for basic unicode characters from plane 0:
```
> rjson::fromJSON("{\"str\" : \"foo \\u02A8\"}")
$str
[1] "foo ʨ"
```

fingers crossed.... if rjson returns the correct utf-8 encoded string, it should look like the following (which can be pasted directly into R and produces the correct unicode:
```
> "Anaheim Ducks \xf0\x9f\x98\x8e"
[1] "Anaheim Ducks 😎"
```

So there's definitely a bug in the handling of surrogate pairs. Thanks for the report. I'll see what can be done, but i'm pretty busy of late. I'll gladly look over any PRs if you can't wait.

Thanks for the report.

**Comment by jefshe** [comment]
Thanks for releasing this @alexcb !

**Comment by alexcb** [comment]
glad to get an update released -- it's been a while :sunglasses: 

Thanks for the PR.
