### ISSUE TITLE
Feature request: a multiline JSON output

### ISSUE THREAD

**Issue by kforner** [alexcb/rjson#14]
Hi,

I really like rjson, especially its speed and reliability. 
One thing that could be improved though: the output of `toJSON()` is a one-line string, and as such is not human readable.
For example, if you save your JSON to a file:
- if you want to quickly have a glance at your data, this long line is not readable.
- if you have saved many JSON files, and want to explore using command-line commands such as `grep`, it will match all the file or nothing. 

I have my own workaround that post-processes the `toJSON()` ouput, but it would be nice to have it properly and natively implemented, maybe controlled by an argument.
What do you think ?

**Comment by alexcb** [comment]
This seems like a very reasonable request, perhaps we can have an optional `indent` argument, which would be similar to python's pprint indent argument. When specified, list items will be printed on separate lines with the appropriate level of indentation.

In terms of using json on the command line, take a look at the jq program; e.g. `cat data.json | jq . | grep foo`

**Comment by kforner** [comment]
>  optional indent

Yes that would be perfect !

>  jq

Thank you for reminding me of this useful program. Does not really solve the `grep -r` use case though.

**Comment by alexcb** [comment]
feature implemented in https://github.com/alexcb/rjson/commit/6130db1b7ab49271c5e84133de7c6ce4f8eb21e0

**Comment by alexcb** [comment]
I'll close this ticket once it's up on cran, cheers.

**Comment by kforner** [comment]
Cool ! Thanks a lot.

Le ven. 8 juin 2018 00:32, Alex Couture-Beil <notifications@github.com> a
écrit :

**Comment by alexcb** [comment]
looks like it's up on cran now:

```> cat(toJSON(list(a="hello", b=c(1,2,99)), indent=4))
{
    "a":"hello",
    "b":[
        1,
        2,
        99
    ]
}```
