### ISSUE TITLE
[minor] couple of compiler warnings

### ISSUE THREAD

**Issue by dselivanov** [alexcb/rjson#16]
Hi @alexcb . Thanks for great work. I see couple of compiler warnings:

> parser.c: In function ‘hasClass’:
parser.c:68:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for( i = 0; i < size; i++ ) {
                ^

> parser.c: In function ‘UTF8EncodeUnicode’:
parser.c:112:40: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
   s[ 1 ] = (MASKBYTE | ( input >> 12 ) & MASKBITS );

I think would be nice to fix.

**Comment by alexcb** [comment]
thanks for the note. fixed in b57dcc9
