### ISSUE TITLE
investigate "String is not utf8" error on what appears to be valid utf8 data

### ISSUE THREAD

**Issue by alexcb** [alexcb/rjson#20]
ibrary(base64enc)
    library(rjson)
    rjson::toJSON(rawToChar(base64decode("8JCNg/CQjL7wkIy58JCMuvCQjLDwkIyy8JCNiQ==")))

produces the error:
unable to escape string. String is not utf8

and if I move to bash, I see it's being decoded correctly:

    $ echo 8JCNg/CQjL7wkIy58JCMuvCQjLDwkIyy8JCNiQ== | base64 -d
    𐍃𐌾𐌹𐌺𐌰𐌲𐍉

**Comment by brodieG** [comment]
With #23:
```
> fromJSON(toJSON(rawToChar(base64decode("8JCNg/CQjL7wkIy58JCMuvCQjLDwkIyy8JCNiQ=="))))
[1] "𐍃𐌾𐌹𐌺𐌰𐌲𐍉"
```
