### ISSUE TITLE
v3.6.3 version?

### ISSUE THREAD

**Issue by labkey-stuartm** [alexcb/rjson#28]
Hi, we noticed you recently published a new release to CRAN.  Will you be providing a v3.6.3 version?

**Comment by alexcb** [comment]
I wasn't planing on testing against 3.X.

Perhaps https://github.com/alexcb/rjson/blob/main/Earthfile#L1-L3 can be changed to allow testing against an earlier version of R.

If it's possible to show all the existing checks work against an earlier version (and continue to work with 4.X), then I would accept a PR rolling it back.

**Comment by mimi3421** [comment]
Install the older version 0.2.20 from CRAN archive https://cran.r-project.org/src/contrib/Archive/rjson/rjson_0.2.20.tar.gz if it's needed by some old packages in R 3.6.
