### ISSUE TITLE
R dependency >= 4.4.0

### ISSUE THREAD

**Issue by jokergoo** [alexcb/rjson#31]
Hi,

I just want to ask, since the **rjson** package is becoming a fundamental package in the R package ecosystem, is the R version requirement (>= 4.4.0) in the current CRAN release too strict? Is there any specific feature that is mandatorily bound to R 4.4.0? 

https://github.com/alexcb/rjson/blob/d15d9a8458b22d0720c80813dd9931c9fb3191e6/rjson/DESCRIPTION#L7

It is because there are many scenarios where older versions of R are still used and some packages depend on **rjson** directly or indirectly.

Thanks!
Zuguang

**Comment by alexcb** [comment]
> Is there any specific feature that is mandatorily bound to R 4.4.0?

There isn't any as far as I know. It was only updated to 4.4.0 to match the version of R it was tested in.

It most likely can be lowered; however, I will need to adjust the test scripts to support testing multiple versions of R. Fortunately it looks like https://hub.docker.com/r/rocker/r-base/tags has many different versions that can be tested against.

**Comment by alexcb** [comment]
I just submitted rjson_0.2.22.tar.gz to CRAN.

**Comment by jokergoo** [comment]
Thank you very much!
